apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: my-nginx2
  labels:
    name: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx2
  template:
    metadata:
      namespace: my-nginx2
      labels:
        name: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx
        ports:
        - containerPort: 81

